# set default-terminal
set -g default-terminal "tmux-256color"

# expect UTF-8
# reload conf
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# set history limit
set -g history-limit 5000

# yazi image preview
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

# set leader
set -g prefix C-s

# mouse
set -g mouse on

# put status on bottom
# set -g status-position bottom
set -g status-position top

# enable clipboard
set -g set-clipboard on

# windows stuff
bind n new-window
set -g base-index 1
setw -g pane-base-index 1
setw -g automatic-rename on
set -g renumber-windows on
set -g set-titles on
set -g status-interval 3


# split pane bindings
bind -r C-h split-window -h -b
bind -r C-l split-window -h
bind -r C-j split-window -v
bind -r C-k split-window -v -b

# switch panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# tpm
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-battery'

#catppucchin load
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "basic"
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

# catpuccin config
set -g status-right-length 100
set -g status-left-length 100

# left side
set -g status-left ""

# right side
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_battery}"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
